name: Run Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours

jobs:

  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot
        
    - name: Run Telegram Bot
      run: |
        python nerdbot.py &
        
    - name: Keep workflow alive
      run: |
        while true; do
          sleep 5h # Sleep for 5 hours
          echo "Keeping workflow alive..."
        done &
        
    - name: Wait for background processes
      run: |
        wait
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}